// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.1
// Source: session.proto

package sessionservice

import (
	"context"

	"awesomeProject/session-rpc/awesomeProject/session-rpc/session"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	DeleteReq  = session.DeleteReq
	DeleteResp = session.DeleteResp
	LoadReq    = session.LoadReq
	LoadResp   = session.LoadResp
	Message    = session.Message
	SaveReq    = session.SaveReq
	SaveResp   = session.SaveResp

	SessionService interface {
		// 加载会话历史
		Load(ctx context.Context, in *LoadReq, opts ...grpc.CallOption) (*LoadResp, error)
		// 保存单条消息
		Save(ctx context.Context, in *SaveReq, opts ...grpc.CallOption) (*SaveResp, error)
		// 删除整个会话
		Delete(ctx context.Context, in *DeleteReq, opts ...grpc.CallOption) (*DeleteResp, error)
	}

	defaultSessionService struct {
		cli zrpc.Client
	}
)

func NewSessionService(cli zrpc.Client) SessionService {
	return &defaultSessionService{
		cli: cli,
	}
}

// 加载会话历史
func (m *defaultSessionService) Load(ctx context.Context, in *LoadReq, opts ...grpc.CallOption) (*LoadResp, error) {
	client := session.NewSessionServiceClient(m.cli.Conn())
	return client.Load(ctx, in, opts...)
}

// 保存单条消息
func (m *defaultSessionService) Save(ctx context.Context, in *SaveReq, opts ...grpc.CallOption) (*SaveResp, error) {
	client := session.NewSessionServiceClient(m.cli.Conn())
	return client.Save(ctx, in, opts...)
}

// 删除整个会话
func (m *defaultSessionService) Delete(ctx context.Context, in *DeleteReq, opts ...grpc.CallOption) (*DeleteResp, error) {
	client := session.NewSessionServiceClient(m.cli.Conn())
	return client.Delete(ctx, in, opts...)
}
