// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.1
// Source: chat.proto

package server

import (
	"context"

	"awesomeProject/chat-rpc/awesomeProject/chat-rpc/chat"
	"awesomeProject/chat-rpc/internal/logic"
	"awesomeProject/chat-rpc/internal/svc"
)

type ChatServiceServer struct {
	svcCtx *svc.ServiceContext
	chat.UnimplementedChatServiceServer
}

func NewChatServiceServer(svcCtx *svc.ServiceContext) *ChatServiceServer {
	return &ChatServiceServer{
		svcCtx: svcCtx,
	}
}

// 流式聊天
func (s *ChatServiceServer) Stream(stream chat.ChatService_StreamServer) error {
	l := logic.NewStreamLogic(stream.Context(), s.svcCtx)
	return l.Stream(stream)
}

// 非流式聊天
func (s *ChatServiceServer) Chat(ctx context.Context, in *chat.ChatReq) (*chat.ChatResp, error) {
	l := logic.NewChatLogic(ctx, s.svcCtx)
	return l.Chat(in)
}
