// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.1
// Source: rag.proto

package ragservice

import (
	"context"

	"awesomeProject/rag-rpc/awesomeProject/rag-rpc/rag"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	BM25SearchReq   = rag.BM25SearchReq
	SearchReq       = rag.SearchReq
	SearchResp      = rag.SearchResp
	VectorSearchReq = rag.VectorSearchReq

	RagService interface {
		// 混合检索（向量+BM25）
		Search(ctx context.Context, in *SearchReq, opts ...grpc.CallOption) (*SearchResp, error)
		// 仅向量检索
		VectorSearch(ctx context.Context, in *VectorSearchReq, opts ...grpc.CallOption) (*SearchResp, error)
		// 仅BM25检索
		BM25Search(ctx context.Context, in *BM25SearchReq, opts ...grpc.CallOption) (*SearchResp, error)
	}

	defaultRagService struct {
		cli zrpc.Client
	}
)

func NewRagService(cli zrpc.Client) RagService {
	return &defaultRagService{
		cli: cli,
	}
}

// 混合检索（向量+BM25）
func (m *defaultRagService) Search(ctx context.Context, in *SearchReq, opts ...grpc.CallOption) (*SearchResp, error) {
	client := rag.NewRagServiceClient(m.cli.Conn())
	return client.Search(ctx, in, opts...)
}

// 仅向量检索
func (m *defaultRagService) VectorSearch(ctx context.Context, in *VectorSearchReq, opts ...grpc.CallOption) (*SearchResp, error) {
	client := rag.NewRagServiceClient(m.cli.Conn())
	return client.VectorSearch(ctx, in, opts...)
}

// 仅BM25检索
func (m *defaultRagService) BM25Search(ctx context.Context, in *BM25SearchReq, opts ...grpc.CallOption) (*SearchResp, error) {
	client := rag.NewRagServiceClient(m.cli.Conn())
	return client.BM25Search(ctx, in, opts...)
}
