// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.19.4
// source: rag.proto

package rag

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SearchReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Query         string                 `protobuf:"bytes,1,opt,name=query,proto3" json:"query,omitempty"`
	TopK          int32                  `protobuf:"varint,2,opt,name=top_k,json=topK,proto3" json:"top_k,omitempty"` // 默认返回数量
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchReq) Reset() {
	*x = SearchReq{}
	mi := &file_rag_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchReq) ProtoMessage() {}

func (x *SearchReq) ProtoReflect() protoreflect.Message {
	mi := &file_rag_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchReq.ProtoReflect.Descriptor instead.
func (*SearchReq) Descriptor() ([]byte, []int) {
	return file_rag_proto_rawDescGZIP(), []int{0}
}

func (x *SearchReq) GetQuery() string {
	if x != nil {
		return x.Query
	}
	return ""
}

func (x *SearchReq) GetTopK() int32 {
	if x != nil {
		return x.TopK
	}
	return 0
}

type SearchResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Chunks        []string               `protobuf:"bytes,1,rep,name=chunks,proto3" json:"chunks,omitempty"`
	SearchTimeMs  float32                `protobuf:"fixed32,2,opt,name=search_time_ms,json=searchTimeMs,proto3" json:"search_time_ms,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchResp) Reset() {
	*x = SearchResp{}
	mi := &file_rag_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchResp) ProtoMessage() {}

func (x *SearchResp) ProtoReflect() protoreflect.Message {
	mi := &file_rag_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchResp.ProtoReflect.Descriptor instead.
func (*SearchResp) Descriptor() ([]byte, []int) {
	return file_rag_proto_rawDescGZIP(), []int{1}
}

func (x *SearchResp) GetChunks() []string {
	if x != nil {
		return x.Chunks
	}
	return nil
}

func (x *SearchResp) GetSearchTimeMs() float32 {
	if x != nil {
		return x.SearchTimeMs
	}
	return 0
}

type VectorSearchReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Query         string                 `protobuf:"bytes,1,opt,name=query,proto3" json:"query,omitempty"`
	TopK          int32                  `protobuf:"varint,2,opt,name=top_k,json=topK,proto3" json:"top_k,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VectorSearchReq) Reset() {
	*x = VectorSearchReq{}
	mi := &file_rag_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VectorSearchReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VectorSearchReq) ProtoMessage() {}

func (x *VectorSearchReq) ProtoReflect() protoreflect.Message {
	mi := &file_rag_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VectorSearchReq.ProtoReflect.Descriptor instead.
func (*VectorSearchReq) Descriptor() ([]byte, []int) {
	return file_rag_proto_rawDescGZIP(), []int{2}
}

func (x *VectorSearchReq) GetQuery() string {
	if x != nil {
		return x.Query
	}
	return ""
}

func (x *VectorSearchReq) GetTopK() int32 {
	if x != nil {
		return x.TopK
	}
	return 0
}

type BM25SearchReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Query         string                 `protobuf:"bytes,1,opt,name=query,proto3" json:"query,omitempty"`
	TopK          int32                  `protobuf:"varint,2,opt,name=top_k,json=topK,proto3" json:"top_k,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BM25SearchReq) Reset() {
	*x = BM25SearchReq{}
	mi := &file_rag_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BM25SearchReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BM25SearchReq) ProtoMessage() {}

func (x *BM25SearchReq) ProtoReflect() protoreflect.Message {
	mi := &file_rag_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BM25SearchReq.ProtoReflect.Descriptor instead.
func (*BM25SearchReq) Descriptor() ([]byte, []int) {
	return file_rag_proto_rawDescGZIP(), []int{3}
}

func (x *BM25SearchReq) GetQuery() string {
	if x != nil {
		return x.Query
	}
	return ""
}

func (x *BM25SearchReq) GetTopK() int32 {
	if x != nil {
		return x.TopK
	}
	return 0
}

var File_rag_proto protoreflect.FileDescriptor

const file_rag_proto_rawDesc = "" +
	"\n" +
	"\trag.proto\x12\x03rag\"6\n" +
	"\tSearchReq\x12\x14\n" +
	"\x05query\x18\x01 \x01(\tR\x05query\x12\x13\n" +
	"\x05top_k\x18\x02 \x01(\x05R\x04topK\"J\n" +
	"\n" +
	"SearchResp\x12\x16\n" +
	"\x06chunks\x18\x01 \x03(\tR\x06chunks\x12$\n" +
	"\x0esearch_time_ms\x18\x02 \x01(\x02R\fsearchTimeMs\"<\n" +
	"\x0fVectorSearchReq\x12\x14\n" +
	"\x05query\x18\x01 \x01(\tR\x05query\x12\x13\n" +
	"\x05top_k\x18\x02 \x01(\x05R\x04topK\":\n" +
	"\rBM25SearchReq\x12\x14\n" +
	"\x05query\x18\x01 \x01(\tR\x05query\x12\x13\n" +
	"\x05top_k\x18\x02 \x01(\x05R\x04topK2\xa1\x01\n" +
	"\n" +
	"RagService\x12)\n" +
	"\x06Search\x12\x0e.rag.SearchReq\x1a\x0f.rag.SearchResp\x125\n" +
	"\fVectorSearch\x12\x14.rag.VectorSearchReq\x1a\x0f.rag.SearchResp\x121\n" +
	"\n" +
	"BM25Search\x12\x12.rag.BM25SearchReq\x1a\x0f.rag.SearchRespB\x1cZ\x1aawesomeProject/rag-rpc/ragb\x06proto3"

var (
	file_rag_proto_rawDescOnce sync.Once
	file_rag_proto_rawDescData []byte
)

func file_rag_proto_rawDescGZIP() []byte {
	file_rag_proto_rawDescOnce.Do(func() {
		file_rag_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_rag_proto_rawDesc), len(file_rag_proto_rawDesc)))
	})
	return file_rag_proto_rawDescData
}

var file_rag_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_rag_proto_goTypes = []any{
	(*SearchReq)(nil),       // 0: rag.SearchReq
	(*SearchResp)(nil),      // 1: rag.SearchResp
	(*VectorSearchReq)(nil), // 2: rag.VectorSearchReq
	(*BM25SearchReq)(nil),   // 3: rag.BM25SearchReq
}
var file_rag_proto_depIdxs = []int32{
	0, // 0: rag.RagService.Search:input_type -> rag.SearchReq
	2, // 1: rag.RagService.VectorSearch:input_type -> rag.VectorSearchReq
	3, // 2: rag.RagService.BM25Search:input_type -> rag.BM25SearchReq
	1, // 3: rag.RagService.Search:output_type -> rag.SearchResp
	1, // 4: rag.RagService.VectorSearch:output_type -> rag.SearchResp
	1, // 5: rag.RagService.BM25Search:output_type -> rag.SearchResp
	3, // [3:6] is the sub-list for method output_type
	0, // [0:3] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_rag_proto_init() }
func file_rag_proto_init() {
	if File_rag_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_rag_proto_rawDesc), len(file_rag_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_rag_proto_goTypes,
		DependencyIndexes: file_rag_proto_depIdxs,
		MessageInfos:      file_rag_proto_msgTypes,
	}.Build()
	File_rag_proto = out.File
	file_rag_proto_goTypes = nil
	file_rag_proto_depIdxs = nil
}
