// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.1
// Source: chat.proto

package chatservice

import (
	"context"

	"awesomeProject/chat-rpc/awesomeProject/chat-rpc/chat"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	ChatChunk   = chat.ChatChunk
	ChatMessage = chat.ChatMessage
	ChatReq     = chat.ChatReq
	ChatResp    = chat.ChatResp

	ChatService interface {
		// 流式聊天
		Stream(ctx context.Context, opts ...grpc.CallOption) (chat.ChatService_StreamClient, error)
		// 非流式聊天
		Chat(ctx context.Context, in *ChatReq, opts ...grpc.CallOption) (*ChatResp, error)
	}

	defaultChatService struct {
		cli zrpc.Client
	}
)

func NewChatService(cli zrpc.Client) ChatService {
	return &defaultChatService{
		cli: cli,
	}
}

// 流式聊天
func (m *defaultChatService) Stream(ctx context.Context, opts ...grpc.CallOption) (chat.ChatService_StreamClient, error) {
	client := chat.NewChatServiceClient(m.cli.Conn())
	return client.Stream(ctx, opts...)
}

// 非流式聊天
func (m *defaultChatService) Chat(ctx context.Context, in *ChatReq, opts ...grpc.CallOption) (*ChatResp, error) {
	client := chat.NewChatServiceClient(m.cli.Conn())
	return client.Chat(ctx, in, opts...)
}
