// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.1
// Source: rag.proto

package server

import (
	"context"

	"awesomeProject/rag-rpc/awesomeProject/rag-rpc/rag"
	"awesomeProject/rag-rpc/internal/logic"
	"awesomeProject/rag-rpc/internal/svc"
)

type RagServiceServer struct {
	svcCtx *svc.ServiceContext
	rag.UnimplementedRagServiceServer
}

func NewRagServiceServer(svcCtx *svc.ServiceContext) *RagServiceServer {
	return &RagServiceServer{
		svcCtx: svcCtx,
	}
}

// 混合检索（向量+BM25）
func (s *RagServiceServer) Search(ctx context.Context, in *rag.SearchReq) (*rag.SearchResp, error) {
	l := logic.NewSearchLogic(ctx, s.svcCtx)
	return l.Search(in)
}

// 仅向量检索
func (s *RagServiceServer) VectorSearch(ctx context.Context, in *rag.VectorSearchReq) (*rag.SearchResp, error) {
	l := logic.NewVectorSearchLogic(ctx, s.svcCtx)
	return l.VectorSearch(in)
}

// 仅BM25检索
func (s *RagServiceServer) BM25Search(ctx context.Context, in *rag.BM25SearchReq) (*rag.SearchResp, error) {
	l := logic.NewBM25SearchLogic(ctx, s.svcCtx)
	return l.BM25Search(in)
}
