// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.1
// Source: session.proto

package server

import (
	"context"

	"awesomeProject/session-rpc/awesomeProject/session-rpc/session"
	"awesomeProject/session-rpc/internal/logic"
	"awesomeProject/session-rpc/internal/svc"
)

type SessionServiceServer struct {
	svcCtx *svc.ServiceContext
	session.UnimplementedSessionServiceServer
}

func NewSessionServiceServer(svcCtx *svc.ServiceContext) *SessionServiceServer {
	return &SessionServiceServer{
		svcCtx: svcCtx,
	}
}

// 加载会话历史
func (s *SessionServiceServer) Load(ctx context.Context, in *session.LoadReq) (*session.LoadResp, error) {
	l := logic.NewLoadLogic(ctx, s.svcCtx)
	return l.Load(in)
}

// 保存单条消息
func (s *SessionServiceServer) Save(ctx context.Context, in *session.SaveReq) (*session.SaveResp, error) {
	l := logic.NewSaveLogic(ctx, s.svcCtx)
	return l.Save(in)
}

// 删除整个会话
func (s *SessionServiceServer) Delete(ctx context.Context, in *session.DeleteReq) (*session.DeleteResp, error) {
	l := logic.NewDeleteLogic(ctx, s.svcCtx)
	return l.Delete(in)
}
